### ISSUE TITLE
How to transmit a CEC Frame?

### ISSUE THREAD

**Issue by ghost** [lucadentella/ArduinoLib_CEClient#3]
I understand this not the best place to ask questions but instead is for reporting bugs, I am hoping you can oblige anyhow. I have very little programming knowledge and understanding. I am trying to create a simple sketch which will transmit a cec frame to play and pause my chromecast when receiving a IR signal (my really old tv doesnt support dec controls only on and off) but I am unsure of how to write the syntax, any help you can provide in pointing me in the correct direction would be greatly appreciated.
EDIT: I should clarify that I already have a working sketch which performs actions when receiving the correct IR signal, my exact problem is how exactly to use the cec library to transmit a frame

**Comment by lucadentella** [comment]
Hi, I'm still working on this library so please consider it very experimental... this is the reason why documentations and examples are still missing.

Anyway to transmit a frame you can call the method:
```cpp
write(int targetAddress, unsigned char* buffer, int count);
```
buffer contains the payload (you can use [CEC-o-matic](http://www.cec-o-matic.com/) to create it) and count is its length.

The method is asynchronous, so if you want to "know" when it completes, you can attach a callback function with the following:
```cpp
void onTransmitCompleteCallback(OnTransmitCompleteCallbackFunction);
```
Hope this week I'll have time to improve the documentation!

**Comment by ghost** [comment]
> 
> 
> Hi, I'm still working on this library so please consider it very experimental... this is the reason why documentations and examples are still missing.
> 
> Anyway to transmit a frame you can call the method:
> 
> ```c++
> write(int targetAddress, unsigned char* buffer, int count);
> ```
> 
> buffer contains the payload (you can use [CEC-o-matic](http://www.cec-o-matic.com/) to create it) and count is its length.
> 
> The method is asynchronous, so if you want to "know" when it completes, you can attach a callback function with the following:
> 
> ```c++
> void onTransmitCompleteCallback(OnTransmitCompleteCallbackFunction);
> ```
> 
> Hope this week I'll have time to improve the documentation!

Thank you for response and help, much appreciated.
