### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by harymk** [lucadentella/ArduinoLib_CEClient#7]
Can you give me hardware connection details and serial print while receiving signal example code

**Comment by lucadentella** [comment]
Hi, you can find the schematics for the interface in Florian Echtler repository: https://github.com/floe/CEC

**Comment by harymk** [comment]
Ok, serial print incoming commands

**Comment by harymk** [comment]
Hello how to add function for recieved data

**Comment by lucadentella** [comment]
You can use the onReceiveCallback(OnReceiveCallbackFunction) method. See CEClient.h for the signature of the callback function

**Comment by lucadentella** [comment]
You can also see the OnReceive method which is the default callback (if no custom functions are defined):

https://github.com/lucadentella/ArduinoLib_CEClient/blob/686166c5d20bde6941590d1bdcfda32261f5394d/src/CEC/CEC_Device.cpp#L45

**Comment by harymk** [comment]
> You can use the onReceiveCallback(OnReceiveCallbackFunction) method. See CEClient.h for the signature of the callback function

can you give me a example

**Comment by harymk** [comment]
```

#include "CEClient.h"

#define CEC_PHYSICAL_ADDRESS    0x1000
#define CEC_INPUT_PIN           2
#define CEC_OUTPUT_PIN          3

// create a CEC client
CEClient ceclient(CEC_PHYSICAL_ADDRESS, CEC_INPUT_PIN, CEC_OUTPUT_PIN);


void setup() {

    Serial.begin(115200);

    // initialize the client with the default device type (PLAYBACK)
    ceclient.begin();

    // enable promiscuous mode (print all the incoming messages)
    ceclient.setPromiscuous(true);

    // enable monitor mode (do not transmit)
    ceclient.setMonitorMode(true);
    ceclient.onReceiveCallback(OnReceiveCallbackFunction);
}

void loop() {

    // run the client
    ceclient.run();
}

 void OnReceiveCallbackFunction(int source, int dest, unsigned char* buffer, int count){
   
 }
```

is this ok

**Comment by harymk** [comment]
Its working thanks for your library and help
