### ISSUE TITLE
esp32

### ISSUE THREAD

**Issue by harymk** [lucadentella/ArduinoLib_CEClient#8]
how to use this library in esp32

**Comment by lucadentella** [comment]
Never tried but... what error do you get? Doesn't it compile?

**Comment by harymk** [comment]
`WARNING: library CEClient claims to run on avr architecture(s) and may be incompatible with your current board which runs on esp32 architecture(s).`

ok in compiling,

**Comment by harymk** [comment]
Sir, its working with esp32. Why its showing not compatible list.
